// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"go-zeroframework/demo/video/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/videos/:id",
				Handler: getVideoHandler(serverCtx),
			},
		},
	)
}
