// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: user.proto

package server

import (
	"context"

	"go-zeroframework/rpc_study/user_group/rpc/internal/logic/useraction"
	"go-zeroframework/rpc_study/user_group/rpc/internal/svc"
	"go-zeroframework/rpc_study/user_group/rpc/types/user"
)

type UserActionServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserActionServer
}

func NewUserActionServer(svcCtx *svc.ServiceContext) *UserActionServer {
	return &UserActionServer{
		svcCtx: svcCtx,
	}
}

func (s *UserActionServer) UserCreate(ctx context.Context, in *user.UserCreateRequest) (*user.UserCreateResponse, error) {
	l := useractionlogic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}
