// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type UserCreateRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type UserInfoRequest struct {
	ID uint `path:"id"`
}

type UserInfoResponse struct {
	UserId   uint   `json:"user_id"`
	UserName string `json:"user_name"`
}
